baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "MineBill's Blog"

theme = "paper"

[params]
color = "gray"

name = "MineBill"
bio = "Tutorials and stuff."

github = "MineBill"

rss = true
monoDarkIcon = true

[params.giscus]
repo = 'MineBill/mineblog'                 # see https://giscus.app for more details
repoId = 'R_kgDOKgN9RQ'
category = 'Blog Comments'
categoryId = 'DIC_kwDOKgN9Rc4CaINl'
mapping = 'pathname'
theme = 'preferred_color_scheme'
lang = "en"